// <auto-generated />
using System;
using L00188315_Project.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L00188315_Project.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250325203856_ConsentTimeStamps")]
    partial class ConsentTimeStamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L00188315_Project.Core.Entities.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountSubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("ConsentId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Balance", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BalanceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Consent", b =>
                {
                    b.Property<string>("ConsentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ConsentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scopes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsentId");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Transaction", b =>
                {
                    b.Property<string>("TransctionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BookingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditDebitIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditorAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebtorAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProprietaryBankTransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProprietaryBankTransactionIssuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValueDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TransctionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Account", b =>
                {
                    b.HasOne("L00188315_Project.Core.Entities.Consent", null)
                        .WithMany("Account")
                        .HasForeignKey("ConsentId");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Balance", b =>
                {
                    b.HasOne("L00188315_Project.Core.Entities.Account", "Account")
                        .WithOne("Balance")
                        .HasForeignKey("L00188315_Project.Core.Entities.Balance", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Transaction", b =>
                {
                    b.HasOne("L00188315_Project.Core.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Account", b =>
                {
                    b.Navigation("Balance");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("L00188315_Project.Core.Entities.Consent", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
