# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  workflow_dispatch:
  # manual trigger only until I can verify approval
  pull_request:
    branches: [ "main" ]
    types: [ opened , ]

permissions: write-all

jobs:
  analyse:
    name: Analyse Code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' , 'typescript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      
    - name: Setup .NET
      if: ${{matrix.language == 'csharp'}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      if: ${{matrix.language == 'csharp'}}
      run: dotnet build -c 'API Only'

    - name: Setup Node
      if: ${{matrix.language == 'typescript'}}
      uses: actions/setup-node@v4
      with:
       node-version: '22'

    - name: Build Angular
      if: ${{matrix.language == 'typescript'}}
      run: |
        cd l00188315_project.client
        npm ci
        npm run build --output-path=./dist
  
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  test:
    runs-on: ${{matrix.os}}
    needs: analyse
    strategy:
       fail-fast: false
       matrix:
          os: [windows-latest,ubuntu-latest]
    timeout-minutes: 5 # this should take no more than 5 mins

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore .

    - name: Compile
      run: dotnet build -c 'API Only' --no-restore #-warnaserror # build backend ONLY
      #Warning acts as an error
    
    - name: Test
      run: dotnet test 