# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
#  push:
#    branches: [ "main" ] # Do not run when code manually pushed to main
  pull_request:
    branches: [ "main" ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ${{matrix.os}}

    strategy:
       fail-fast: false
       matrix:
          os: [windows-latest,ubuntu-latest]
    timeout-minutes: 5 # this should take no more than 5 mins

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Compile
      run: dotnet build -c Debug #-warnaserror 
      #Warning acts as an error
    
    - name: Test
      run: dotnet test 

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure
        run: echo This will deploy in the future