# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  workflow_dispatch:
  # manual trigger only until I can verify approval
  pull_request:
    branches: [ "main" ]
    types: [opened,closed]

permissions: write-all

jobs:
  test:
    #run when opened
    if: github.event.pull_request.merged == false 
    runs-on: ${{matrix.os}}

    strategy:
       fail-fast: false
       matrix:
          os: [windows-latest,ubuntu-latest]
    timeout-minutes: 5 # this should take no more than 5 mins

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore .

    - name: Compile
      run: dotnet build -c 'API Only' --no-restore #-warnaserror # build backend ONLY
      #Warning acts as an error
    
    - name: Test
      run: dotnet test 

  build:
    #run when closed + merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build project artefact
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup .Node
      uses: actions/setup-node@v4
      with:
       node-version: '22'

    - name: Restore dependencies
      run: dotnet restore .

    - name: Build Angular
      run: |
        cd l00188315_project.client
        npm ci
        npm run build
        cd ..

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --property:PublishDir=./app
      
    - name: List App Directory
      run: ls -la ./L00188315_Project.Server/app/
      continue-on-error: true

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: "publish"
        path: ./L00188315_Project.Server/app/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: "publish"
          path: ./app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7126B6E6242F41278650E774CACCFCF8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A34E9AB11A5A4F979CC46A3C8E075855 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AD9FFD26BFF47FFABF78A86999164E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{vars.APP_NAME}}
          package: ./app
          