# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Integration

on: 
  workflow_dispatch:
  # manual trigger only until I can verify approval
  pull_request:
    branches: [ "main" ]
    types: [ opened ]

permissions: write-all

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
       fail-fast: false
       matrix:
          os: [windows-latest,ubuntu-latest ]
    timeout-minutes: 5 # this should take no more than 5 mins

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore project dependencies
      run: dotnet restore .

    - name: Compile Backend Application
      run: dotnet build -c 'API Only' --no-restore -warnaserror # build backend ONLY

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0 
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      continue-on-error: true

     #Run Tests
    - name: Test Dotnet Application
      run: dotnet test --logger "trx;LogFileName=TestResults-${{matrix.os}}.trx"
      #Upload test results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: test-results-${{matrix.os}}
        path: ${{github.workspace}}/Project_Tests/TestResults/TestResults-${{matrix.os}}.trx
