# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  workflow_dispatch:
  # manual trigger only until I can verify approval
  # pull_request:
  #   branches: [ "main" ]

permissions: write-all

jobs:
  test:
    runs-on: ${{matrix.os}}

    strategy:
       fail-fast: false
       matrix:
          os: [windows-latest,ubuntu-latest]
    timeout-minutes: 5 # this should take no more than 5 mins

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore .

    - name: Compile
      run: dotnet build -c 'API Only' --no-restore #-warnaserror # build backend ONLY
      #Warning acts as an error
    
    - name: Test
      run: dotnet test 

  build:
    
    runs-on: ubuntu-latest
    name: Build project artefact
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore .

    - name: Compile
      run: dotnet build -c Release --no-restore #-warnaserror #Warning acts as an error

    - name: Publish
      run: | 
        dotnet publish 
        --configuration Release 
        --no-restore
        --no-build
        --property:PublishDir=./app
      
    - name: List App Directory
      run: ls -R ./app

    - name: Remove un-needed runtime configs
      run: rm ./app/L00188315_Project.Infrastructure.runtimeconfig.json
      continue-on-error: true

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: "publish"
        path: ./app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: "publish"
          path: ./app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7126B6E6242F41278650E774CACCFCF8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A34E9AB11A5A4F979CC46A3C8E075855 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AD9FFD26BFF47FFABF78A86999164E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{vars.APP_NAME}}
          package: ./app
          