name: Terraform Create

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      
permissions:
  id-token: write
  contents: read
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo    
          uses: actions/checkout@v4
        
        - name: "Install Terraform"
          uses: hashicorp/setup-terraform@v3

        - name: Azure CLI Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            enable-AzPSSession: true
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Terraform Init
          run: terraform -chdir=terraform/ init
          
        - name: Terraform Plan
          id: plan
          run: terraform -chdir=terraform/ plan -var="location=europe-north" -var="prefix=atu_" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan

