name: Terraform Create

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      
permissions:
  id-token: write
  contents: read
        
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repo    
          uses: actions/checkout@v4
          env:
              GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
              REPO: ${{ github.event.repository.name }}
        
        - name: "Install Terraform"
          uses: hashicorp/setup-terraform@v3

        - name: Azure CLI Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            enable-AzPSSession: true
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Terraform Init
          run: terraform -chdir=terraform/ init
          
        - name: Terraform Plan
          id: plan
          run: terraform -chdir=terraform/ plan -var="location=northeurope" -var="prefix=atu" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan
        - name: Terraform Apply
          id: apply
          run: terraform -chdir=terraform/ apply "tfplan"
        - name: Save outputs
          continue-on-error: true #this might fail, but thats okay.
          id: output
          run: |
            echo | terraform output app_name
            echo | terraform output app_url
            gh variable set APP_NAME --body | terraform output app_name
            gh variable set APP_URL --body | terraform output app_url
          

