name: Terraform Create

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      inputs: 
        location:
          description: 'Location of the resources'
          required: true
          default: 'northeurope'
        prefix:
          description: 'Prefix for the resources'
          required: true
          default: 'atu'
        os:
          description: 'Operating System for the resource - Windows or Linux'
          required: true
          default: 'Windows'
      
permissions: write-all
        
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repo    
          uses: actions/checkout@v4
          env:
              GH_TOKEN: ${{ github.token }}
              REPO: ${{ github.event.repository.name }}
        
        - name: "Install Terraform"
          uses: hashicorp/setup-terraform@v3

        - name: Azure CLI Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            enable-AzPSSession: true
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Terraform Init
          run: terraform -chdir=terraform/ init
          
        - name: Terraform Plan
          id: plan
          run: terraform -chdir=terraform/ plan -var="os=${{ inputs.os }}" -var="location=${{ inputs.location }}" -var="prefix=${{ inputs.prefix }}" -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out=tfplan
        - name: Terraform Apply
          id: apply
          run: terraform -chdir=terraform/ apply "tfplan"
        - name: Save outputs
          continue-on-error: true #this might fail, but thats okay.
          id: output
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN_PAT }}
          run: |
            cd terraform/
            app_name=$(terraform output -raw app_name)
            app_url=$(terraform output -raw app_url)
            gh variable set APP_NAME --body "$app_name"
            gh variable set APP_URL --body "$app_url"
          

