name: Terraform Create

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo    
          uses: actions/checkout@v4
        
        - name: "Install Terraform"
          uses: hashicorp/setup-terraform@v3

        - name: "Install Azure CLI"
          uses: azure/setup-azure-cli@v1
          with:
            version: latest

        - name: "Login to Azure"
          run: |
            echo "TBD"

        - name: Update CWD
          run: terraform -chdir=terraform/ init
          
        - name: Terraform init
          id: init
          run: terraform -chdir=terraform/ plan -var="location=europe-north" -var="prefix=atu_"

